### ISSUE TITLE
Use of Template?

### ISSUE THREAD

**Issue by sysads** [roaminggamer/CoronaGeek#2]
Hi

Can I use this zigzag template for my game? I am new to corona and was hoping to integrate ads, leaderboard score and sound effect as a learning curve.

I see this is similar to zig zag boom so was wondering if I would be allowed to use the same glowing ball.

Thanks

**Comment by CharlesMcKeever** [comment]
Hi sysads. Yes, you can use this template as a starting point for your game. As you've mentioned, I highly recommend customizing the game to add features and make the game your own. Changing the colors would be good as well. As for the particle effects, you can tweak those as well.  We talked about creating particle effects back on Hangout 82, so be sure to check out that video for a look at some particle designer tools, https://coronalabs.com/blog/coronageek/corona-geek-hangout-82/. Let us know when you publish your game so we can talk about it on the show :)

**Comment by sysads** [comment]
Thanks Charles, you guys are amazing. If I am to add a pickup at certain intervals just to lower speed of the player for a defined time frame, where can i do that.

Also how do i change the buttons to png files?

Thanks
